#!/usr/bin/env python

import knowledge_representation
import rospy
import smach_ros
from knowledge_representation import LongTermMemoryConduit
from smach import StateMachine, State
from geometry_msgs.msg import Point

from bwi_tasks.common import states, control_flow, task_machine
from bwi_tasks.experiment import utils
from bwi_kr_execution import goal_formulators, knowledge

def main():
    rospy.init_node("tmp_demo_smach")
    target = rospy.get_param("~location", "l3_414b")

    print(target)

    if not target:
        print("Please provide a location: location:=d3_414b1")

    simulation = rospy.get_param("~simulation", False)
    introspect = rospy.get_param("~introspect", False)
    State.simulation = simulation

    ltmc = knowledge_representation.get_default_ltmc()

    task_machine.get_recover_from_failure_sm(ltmc)

    # Create top state machine
    sm = StateMachine(outcomes=['succeeded', 'preempted', 'aborted'])
    # Open the container
    with sm:
        run_repeat_gate = control_flow.RepeatN(1)
        StateMachine.add_auto("LAUNCH_PLAN_EXECUTOR", 
            utils.LaunchPlanExecutor(simulation, True, True), ["succeeded"])
        
        episode_repeat_gate = control_flow.RepeatN(15)
        StateMachine.add_auto("CLEAN_EPISODE_REPEAT", control_flow.ResetRepeat(episode_repeat_gate), ["succeeded"])
        StateMachine.add("INITIALIZE_ROBOT1", states.MoveToPosition(), transitions={"succeeded": "CLEAR_COSTMAP",
										   "aborted": "WAIT"})
	StateMachine.add_auto("WAIT", control_flow.Sleep(90), ["succeeded"])
	StateMachine.add_auto("INITIALIZE_ROBOT2", states.MoveToPosition(), ["succeeded"])
        StateMachine.add_auto("CLEAR_COSTMAP", states.ClearCostmap(), ["succeeded"])
        #StateMachine.add_auto("CLOSE_DOORS", states.CloseDoor(), ["succeeded"])
        control_flow.inject_userdata_auto("INJECT_LOCATION", "location", target)
        StateMachine.add('GOTO_LOCATION', task_machine.generate_goal_based_task_sm(
            goal_formulators.GoToRoomOrLocationName(ltmc), ["location"]),
            transitions={"succeeded": "EPISODE_REPEAT",
                         "aborted": "EPISODE_REPEAT"})
        StateMachine.add("EPISODE_REPEAT", episode_repeat_gate, 
            transitions={"repeat": "INITIALIZE_ROBOT1", "done": "SHUTDOWN_PLAN_EXECUTOR"})

        StateMachine.add_auto("SHUTDOWN_PLAN_EXECUTOR", utils.ShutdownPlanExecutor(), ["succeeded"])

    if introspect:
        sis = smach_ros.IntrospectionServer('introspection_server', sm, '/SM_ROOT')
        sis.start()

    # Execute SMACH plan
    outcome = sm.execute()

    if introspect:
        rospy.spin()
        sis.stop()


if __name__ == '__main__':
    main()
